import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@ui/Header";
import { LayoutContainer, Divider, MainContainer } from "./layout.style";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutContainer>
          <Header logo={"/main-logo.png"} />
          <Divider />
          <MainContainer>{children}</MainContainer>
        </LayoutContainer>
      </body>
    </html>
  );
}
